name: Apps
options:
  bundleIdPrefix: com.objp.urlsession
  deploymentTarget:
    iOS: 17
settings:
  base:
    GENERATE_INFOPLIST_FILE: true

packages:
  URLSession:
    path: ..

targets:
  iOS:
    type: application
    platform: iOS
    sources: [iOS]
    settings:
      base:
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
        PRODUCT_MODULE_NAME: URLSession
        PRODUCT_NAME: URLSession
    dependencies:
      - package: URLSession
        products: [HTTP]
